# Generated by Django 3.0.4 on 2020-03-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, help_text='Size is measured in cm3', max_digits=2),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_fleet.Car'),
        ),
    ]
