# Generated by Django 3.0.4 on 2020-03-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Jar', 'Jar'), ('Feeder', 'Feeder'), ('Portion', 'Portion'), ('Bottle', 'Bottle'), ('Folic bag', 'Folic Bag'), ('Stoneware', 'Stoneware'), ('Tube', 'Tube')], max_length=20, verbose_name='Package type')),
                ('capacity', models.PositiveSmallIntegerField(help_text='Weight is measered in grams or liters', verbose_name='Package weight')),
                ('capacity_type', models.CharField(choices=[('g', 'G'), ('l', 'L')], max_length=1, verbose_name='Package weight type')),
                ('multipack_quantity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This describe name of specific product', max_length=128, verbose_name='Product name')),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat', models.PositiveSmallIntegerField(choices=[(1, 0.23), (2, 0.08), (3, 0.05), (4, 0.0)])),
                ('have_promotion', models.BooleanField(default=False)),
                ('packages', models.ManyToManyField(to='product.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Promotion name')),
                ('discount', models.FloatField(default=1.0, help_text='Describe promotion value i.e. 1 means no promotion, 0.95 means 5% discount')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
