# Generated by Django 3.0.4 on 2020-03-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packages',
        ),
        migrations.AddField(
            model_name='product',
            name='packages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Package'),
            preserve_default=False,
        ),
    ]
