# Generated by Django 3.0.4 on 2020-03-08 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Document title')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateField(verbose_name='Document created day')),
                ('type', models.CharField(choices=[('C', 'Cash'), ('N', 'No Cash')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_station', models.CharField(choices=[('DIR', 'Director'), ('MAN', 'Manager'), ('SAG', 'Sales Agent')], default='SAG', max_length=3)),
                ('region', models.CharField(choices=[('DSL', 'Dolnoslaskie'), ('K-P', 'Kujawsko Pomorskie'), ('LBL', 'Lubelskie'), ('LBU', 'Lubuskie'), ('LDZ', 'Lodzkie'), ('MLP', 'Malopolskie'), ('MAZ', 'Mazowieckie'), ('OPO', 'Opolskie'), ('PKR', 'Podkarpackie'), ('PDL', 'Podlaskie'), ('POM', 'Pomorskie'), ('SL', 'Slaskie'), ('SW', 'Swietokrzyskie'), ('W-M', 'Warminsko Mazurskie'), ('WLKP', 'Wielkopolskie'), ('ZPM', 'Zachodniopomorskie')], max_length=4)),
                ('phone_number', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
