# Generated by Django 3.0.4 on 2020-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_document_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_station',
            field=models.CharField(choices=[('DIR', 'Director'), ('MAN', 'Manager'), ('SAG', 'Sales agent')], default='SAG', max_length=3),
        ),
    ]
