# Generated by Django 3.1.14 on 2022-05-10 07:22
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension()
    ]
