# Generated by Django 3.1.14 on 2022-05-10 15:43

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_postgres_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(error_messages={'unique': 'User with that email already exists'}, max_length=100, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('date_start_job', models.DateField(blank=True, null=True)),
                ('date_end_job', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(choices=[('DSL', 'Dolnoslaskie'), ('K-P', 'Kujawsko Pomorskie'), ('LBL', 'Lubelskie'), ('LBU', 'Lubuskie'), ('LDZ', 'Lodzkie'), ('MLP', 'Malopolskie'), ('MAZ', 'Mazowieckie'), ('OPO', 'Opolskie'), ('PKR', 'Podkarpackie'), ('PDL', 'Podlaskie'), ('POM', 'Pomorskie'), ('SL', 'Slaskie'), ('SW', 'Swietokrzyskie'), ('W-M', 'Warminsko Mazurskie'), ('WLKP', 'Wielkopolskie'), ('ZPM', 'Zachodniopomorskie')], help_text='Determines the area in which the sales agent works', max_length=4)),
                ('role', models.CharField(choices=[('DIR', 'Director'), ('MAN', 'Manager'), ('SAG', 'Sales agent')], default='SAG', help_text='Determines the user role in company', max_length=3)),
                ('phone_number', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Determines if the user has an active account', verbose_name='account status')),
                ('admin', models.BooleanField(default=False, help_text='Determines if the user is superuser and can manage the admin panel', verbose_name='admin status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
